name: fleur
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  flavor: ^2.0.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  meta: ^1.10.0
  firebase_core: ^2.25.4
  shimmer: ^3.0.0
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.8
  package_info_plus: ^5.0.1
  logger: ^2.1.0
  integration_test:
    sdk: flutter
  # equatable: ^2.0.5
  # cloud_firestore: ^4.15.4
  # firebase_core: ^2.25.4
  # firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

