// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IxCSbJpoI4wepb3BT2izVVuH07sFARs',
    appId: '1:346305233623:web:bd6652124bd89125116692',
    messagingSenderId: '346305233623',
    projectId: 'fleur-a-new-journey',
    authDomain: 'fleur-a-new-journey.firebaseapp.com',
    storageBucket: 'fleur-a-new-journey.appspot.com',
    measurementId: 'G-64E7G7C14C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVG0wi53ExC8QMMRbv63SuSiu10AnWap0',
    appId: '1:346305233623:android:145913c887324465116692',
    messagingSenderId: '346305233623',
    projectId: 'fleur-a-new-journey',
    storageBucket: 'fleur-a-new-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-gk8U3pbMQK0BWqn3qvooXxvNqNf3W4',
    appId: '1:346305233623:ios:561c59d7a8e615b7116692',
    messagingSenderId: '346305233623',
    projectId: 'fleur-a-new-journey',
    storageBucket: 'fleur-a-new-journey.appspot.com',
    iosClientId: '346305233623-t50v60kqllvha2l7u2apredo2erlomck.apps.googleusercontent.com',
    iosBundleId: 'com.fleur.app',
  );
}
